global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: webhook-delivery-platform
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["backend:8080"]
